//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneal.JsUnitUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sneal.JsUnitUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry=&lt;script language=&apos;javascript&apos; src=&apos;file:///{0}&apos;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposedTestFunctionBlock=&lt;script&gt;        ///\nfunction exposeTestFunctionNames()        ///\n{{        ///\nvar testFuncs = new Array();        ///\n{0}        ///\nreturn testFuncs;        ///\n}}        ///\n&lt;/script&gt;.
        /// </summary>
        internal static string ExposedTestFunctionBlock {
            get {
                return ResourceManager.GetString("ExposedTestFunctionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposedTestFunctionEntry=testFuncs[{0}] = &quot;{1}&quot;;.
        /// </summary>
        internal static string ExposedTestFunctionEntry {
            get {
                return ResourceManager.GetString("ExposedTestFunctionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsUnitCore=file:///{0}app/jsUnitCore.js.
        /// </summary>
        internal static string JsUnitCore {
            get {
                return ResourceManager.GetString("JsUnitCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsUnitTestRunner=file:///{0}testRunner.html?testpage={1}&amp;autoRun=true.
        /// </summary>
        internal static string JsUnitTestRunner {
            get {
                return ResourceManager.GetString("JsUnitTestRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite=&lt;html&gt;        ///\n &lt;head&gt;        ///\n  &lt;title&gt;Javascript Unit Tests&lt;/title&gt;        ///\n  &lt;script language=&apos;javascript&apos; src=&apos;{0}&apos;&gt;&lt;/script&gt;        ///\n  {1}        ///\n{2}        ///\n &lt;/head&gt;        ///\n &lt;body&gt;        ///\n   &lt;h1&gt;JavaScript Test Suite&lt;/h1&gt;        ///\n   &lt;p&gt;This page contains a suite of test.&lt;/p&gt;	        ///\n &lt;/body&gt;        ///\n&lt;/html&gt;.
        /// </summary>
        internal static string Suite {
            get {
                return ResourceManager.GetString("Suite", resourceCulture);
            }
        }
    }
}
