//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneal.ProxyConsole.Tests.ConsoleRunnerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://proxyconsole.sneal.net", ConfigurationName="ConsoleRunnerService.ConsoleRunner", CallbackContract=typeof(Sneal.ProxyConsole.Tests.ConsoleRunnerService.ConsoleRunnerCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ConsoleRunner {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proxyconsole.sneal.net/ConsoleRunner/Run", ReplyAction="http://proxyconsole.sneal.net/ConsoleRunner/RunResponse")]
        void Run(Sneal.ProxyConsole.WcfService.StartExecutionMessage requestMsg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ConsoleRunnerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://proxyconsole.sneal.net/ConsoleRunner/ExecutionComplete")]
        void ExecutionComplete(Sneal.ProxyConsole.WcfService.ExecutionFinishedMessage completeMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://proxyconsole.sneal.net/ConsoleRunner/ExecutionProgress")]
        void ExecutionProgress(Sneal.ProxyConsole.WcfService.ExecutionProgressMessage progressMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ConsoleRunnerChannel : Sneal.ProxyConsole.Tests.ConsoleRunnerService.ConsoleRunner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConsoleRunnerClient : System.ServiceModel.DuplexClientBase<Sneal.ProxyConsole.Tests.ConsoleRunnerService.ConsoleRunner>, Sneal.ProxyConsole.Tests.ConsoleRunnerService.ConsoleRunner {
        
        public ConsoleRunnerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ConsoleRunnerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ConsoleRunnerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ConsoleRunnerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ConsoleRunnerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Run(Sneal.ProxyConsole.WcfService.StartExecutionMessage requestMsg) {
            base.Channel.Run(requestMsg);
        }
    }
}
